name: initramfs_tools
check_this_dir: /etc/initramfs-tools
enable_lvm:
  - echo "This operations not required."
enable_luks:
  - sed -i "s/^GRUB_THEME=.*/GRUB_THEME=\"\"/g" /target/etc/default/grub
commands:
  - update-initramfs.orig.initramfs-tools -c -t -k all
